In [1]:
import numpy as np

a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [2]:
a=np.array([5,10,15,20,25])
print(a[2])

15


In [5]:
a=np.array([[5,10,15,20,25],[55,110,151,201,25],[65,80,15,20,25]])
print(a)
print("After Slicing")
print(a[:2])

[[  5  10  15  20  25]
 [ 55 110 151 201  25]
 [ 65  80  15  20  25]]
After Slicing
[[  5  10  15  20  25]
 [ 55 110 151 201  25]]


In [6]:
a=np.array([5,10,15,20,25,30])
b=a.reshape(2,3)
print(b)

[[ 5 10 15]
 [20 25 30]]


In [8]:
a=np.array([5,10,15,20,25,30])
b=np.array([55,510,515,520,525,530])
c=np.concatenate((a,b))
print(c)

[  5  10  15  20  25  30  55 510 515 520 525 530]


In [11]:
a=np.array([5,10,15,20,25,30,70])
i=np.where(a>25)
print(i)

(array([5, 6], dtype=int64),)


In [12]:
b=np.array([55,510,515,520,525,530])
c=np.sort(b)
print(c)

[ 55 510 515 520 525 530]


In [15]:
a=np.array([12, 15, 20, 25, 30, 35, 40])
print(a)

new=[]
for i in a:
    if i>25:
        new.append(i)
        
new_array=np.array(new)
print(new_array)
print(type(new_array))

[12 15 20 25 30 35 40]
[30 35 40]
<class 'numpy.ndarray'>


In [20]:
a=np.array([5,10,15,20])
b=np.array([55,510,515,520])
c=a/b
print(c)

[0.09090909 0.01960784 0.02912621 0.03846154]


In [22]:
a=np.array([[5,10],[55,110],[65,80]])
print(a)

print("After Transpose")
print(a.T)

[[  5  10]
 [ 55 110]
 [ 65  80]]
After Transpose
[[  5  55  65]
 [ 10 110  80]]


In [25]:
a=np.array([55,510,515,520])
print(np.min(a))
print(np.max(a))
print(np.mean(a))

55
520
400.0


In [32]:
a=np.array([[5,10],[6,11]])
print(a)
b=np.array([[55,101],[65,111]])
print(b)
print("Aftre Concatenation")
c=np.concatenate((a,b))
print(c)
print("Aftre horizontal Concatenation")
c=np.concatenate((a,b),axis=1)
print(c)

[[ 5 10]
 [ 6 11]]
[[ 55 101]
 [ 65 111]]
Aftre Concatenation
[[  5  10]
 [  6  11]
 [ 55 101]
 [ 65 111]]
Aftre horizontal Concatenation
[[  5  10  55 101]
 [  6  11  65 111]]


In [35]:
a=np.array([25000, 32000, 28000, 45000, 30000, 27000])
print(a)
increment=np.where(a<30000,a*0.1,a*0.05)
print("increment as per policy",increment)

[25000 32000 28000 45000 30000 27000]
increment as per policy [2500. 1600. 2800. 2250. 1500. 2700.]
